import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :aurum, AurumWeb.Endpoint,
  url: [host: "aurum.rizafahmi.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  force_ssl: [hsts: true],
  http: [port: 4000, cipher_suite: :strong, transport_options: [socket_opts: [:inet6]]],
  https: [port: 4040, cipher_suite: :strong, transport_options: [socket_opts: [:inet6]]]

config :aurum, :cert_path, "/home/rizafahmi/site_encrypt_db"
config :aurum, :cert_mode, "production"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
